name: CD - Deploy FlashOffer UI to Vercel

on:
  push:
    branches:
      - testing
      - production

jobs:
  deploy-testing:
    if: github.ref_name == 'testing'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy to Vercel (Testing)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy-production:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build:production

      - name: Deploy to Vercel (Production)
        run: npx vercel@latest --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}